version: '3.4'

services:

  nginx:
    image: "${NGINX_VERSION}"
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/ssl:/etc/nginx/ssl
      - ./log/nginx:/var/log/nginx
      - ./src:/var/www
    restart: on-failure

  mysql:
    image: "${MYSQL_VERSION}"
    privileged: true
    ports:
      - 3306:${MYSQL_PORT}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./etc/mysql/my.cnf.d:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: on-failure

  mongodb:
    image: "${MONGO_VERSION}"
    ports:
      - 27017:${MONGO_PORT}
    command: --config /etc/mongo/mongod.conf
    volumes:
      - ./etc/mongo/conf:/etc/mongo
      - ./data/mongo/db:/data/db
      - ./log/mongo:/var/log/mongodb
    environment:
      TZ: ${TZ}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: on-failure

  redis:
    image: "${REDIS_VERSION}"
    ports:
      - 6379:${REDIS_PORT}
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./etc/redis/conf:/usr/local/etc/redis
      - ./data/redis/data:/data:rw
      - ./log/redis:/logs
    environment:
      TZ: ${TZ}
    restart: on-failure