version: '3.4'

services:

  nginx:
    image: "${NGINX_VERSION}"
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/ssl:/etc/nginx/ssl
      - ./src:/var/www
    restart: on-failure

  mysql:
    image: "${MYSQL_VERSION}"
    privileged: true
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./log/mysql:/var/log/mysql
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./etc/mysql/my.cnf.d:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: on-failure